site_name: Keras中文文档
pages:
- '主页': 'index.md'

- 'keras新手指南':
  - '一些基本概念': 'for_beginners/concepts.md'
  - '常见问题与解答': 'for_beginners/FAQ.md'
  - 'Keras安装和配置指南(Linux)': 'for_beginners/keras_linux.md'
  - 'Keras安装和配置指南(Windows)': 'for_beginners/keras_windows.md'
  - 'Keras使用陷阱': 'for_beginners/trap.md'

- '快速开始':
  - '序贯模型': 'getting_started/sequential_model.md'
  - '函数式模型': 'getting_started/functional_API.md'

- '模型':
  - '关于Keras模型': 'models/about_model.md'
  - '序贯模型API': 'models/sequential.md'
  - '函数式模型API': 'models/model.md'


- '网络层':
  - '关于Keras层': 'layers/about_layer.md'
  - '常用层Core': 'layers/core_layer.md'
  - '卷积层Convolutional': 'layers/convolutional_layer.md'
  - '池化层Pooling': 'layers/pooling_layer.md'
  - '局部连接层Locally-connented': 'layers/locally_connected_layer.md'
  - '循环层Recurrent': 'layers/recurrent_layer.md'
  - '嵌入层Embedding': 'layers/embedding_layer.md'
  - '融合层Merge': 'layers/merge.md'
  - '高级激活层Advanced Activation': 'layers/advanced_activation_layer.md'
  - '规范层BatchNormalization': 'layers/normalization_layer.md'
  - '噪声层Noise': 'layers/noise_layer.md'
  - '包装器Wrapper': 'layers/wrapper.md'
  - '编写自己的层': 'layers/writting_layer.md'

- '数据预处理':
  - '序列预处理': 'preprocessing/sequence.md'
  - '文本预处理': 'preprocessing/text.md'
  - '图片预处理': 'preprocessing/image.md'

- '网络配置':
  - '损失函数loss': 'other/objectives.md'
  - '优化器Optimizer': 'other/optimizers.md'
  - '激活函数Activation': 'other/activations.md'
  - '性能评估Metrices': 'other/metrics.md'
  - '初始化方法Initializers': 'other/initializations.md'
  - '正则项Regularizer': 'other/regularizers.md'
  - '约束项Constraint': 'other/constraints.md'
  - '回调函数Callback': 'other/callbacks.md'

- '协助使用Keras':
  - '预训练模型Application': 'other/application.md'
  - '常用数据库Dataset': 'other/datasets.md'
  - '可视化visualization': 'other/visualization.md'

- '协助使用Keras':
  - '工具': 'utils.md'

- 'keras后端Backend': 'backend.md'
- 'scikit-learn接口': 'scikit-learn_API.md'
- '致谢': 'acknowledgement.md'

theme: readthedocs
site_author: BigMoyan
